name: Hello World Workflow

on:
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: debian-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make Artifact
        run: echo "Hello World" > hello-world.txt

      - name: Example Artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello-world-file
          path: hello-world.txt
